import Head from 'next/head'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Header from '../components/Header'
import LargeCard from '../components/LargeCard'
import MediumCard from '../components/MediumCard'
import SmallCard from '../components/SmallCard'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Airbnb Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Header/>
        <Banner />

        <main className='max-w-7xl mx-auto px-8 sm:px-16'>
            <section className="pt-6">
                <h2 className='text-4xl font-semibold pb-5'> Explore Nearby</h2>
                <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
                  {
                  Array(10).fill().map((_, index)=>(
                    <SmallCard key={index} />
                  ))
                  }
                </div>
            </section>

            <section>
                  <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
                  <div className='flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3'>
                    {
                    Array(8).fill().map((_, index)=>(
                      <MediumCard key={index} />
                    ))
                    }
                  </div>
            </section>

            <LargeCard />
            <Footer />
        </main>

    </div>
  )
}
